{% set name = "pydeck" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 907601c99f7510e16d27d7cb62bfa145216d166a2b5c9c50cfe2b65b032ebd2e

build:
  # noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - ipykernel
    - ipython
    - jinja2
    - pip
    - python
    - traitlets
    - numpy >=1.16.4
  run:
    - python >=3.6
    - ipykernel
    - ipywidgets
    - jinja2
    - python
    - traitlets
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget

about:
  home: https://github.com/uber/deck.gl/tree/master/bindings/pydeck
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://pydeck.gl
  dev_url: https://github.com/uber/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
