{% set name = "pydeck" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e31b190430afde860c5955b63e11bcb5fcc372afef71529d4e9020936af6dbc5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - ipykernel
    - ipython
    - jinja2
    - pip
    - python
    - traitlets
    - numpy >=1.16.4
  run:
    - ipykernel
    - ipywidgets
    - jinja2
    - python
    - traitlets
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget

about:
  home: https://github.com/uber/deck.gl/tree/master/bindings/pydeck
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://pydeck.gl
  dev_url: https://github.com/uber/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
