{% set name = "pydeck" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07edde833f7cfcef6749124351195aa7dcd24663d4909fd7898dbd0b6fbc01ec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - python 
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ipykernel >=5.1.2
    - ipywidgets >=7,<8
    - jinja2 >=2.10.1
    - traitlets >=4.3.2
    - numpy >=1.16.4

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget
  requires:
    - pip
    - ipython_genutils
  commands:
    - pip check

about:
  home: https://github.com/uber/deck.gl/tree/master/bindings/pydeck
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  description: |
    The pydeck library is a set of Python bindings for making spatial visualizations
    with deck.gl, optimized for a Jupyter environment.
  doc_url: https://pydeck.gl
  dev_url: https://github.com/uber/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
