travis:
  secure:
    BINSTAR_TOKEN: oo9J5OHakjOgZMg8ZirKPYItyP5CPVn9aaRGRzg1HNVKa0DZyMuxfOROpLbaYsOkpI2UNC0AtsdCB7wvBP+DlwWIwjlWTjc4BJ5gEbFyBCioxrb1svRop1GstL90tHgtBdwDMHk97QPMHV4O0tqNGJYc77wt3UlZCWAvIFaMYEDJZCtK85hqy6/MbgP9qWf+Zi5PAmmil0KUuL9QsD6zE22Z6ah+5Bs3SajDTvFOTwtyl/yIiol78hwcn/JoOZSVqLqeSbBDawnP5X4wYOtpjB1jibyp6YCDw/hsNLeeiofl8tB5uYuf5mHHvGNnieQZSVYqX6viwN7TUlBvKZ6U/JhzCKaePLY/XYp5lWhk5HKV03DYX55WrgwYiOGKf+QNFET7d4yxVZtmFucrXqZe2CqsO4sS4RSaWwVIEUpz2/yD2ych4e0hEiwGC7b2N8XLczZ1SvY5C1RNYuTh8moR0Wk73uX1IfYynXeRtTKYyI4kep92ZeeZtwP0B26K3mprpYedRt2v/9Uj+BggQwgFhFStOledxjP495QcRQe2YBvTRw5Dk7qlPTztMy8WS+Shn0kR+nLpiyPDsI9Clh5zObz+7KaRW6+eE0PU7gvCKzWRsTZXSBcS1nyNDijnkHHzNVf2iQ+PypWwn9I4fv5XJ0JjYJ5qMxgVJhkcMVUhyq4=
conda_forge_output_validation: true
bot:
  automerge: true
